### ISSUE TITLE
[code-review] Файлы phpStorm в репозитории

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#1]
Папка [.idea](https://github.com/SergeyKozadaev/symfonyLibrary/tree/master/.idea) создаётся редактором phpStorm. Подобные папки не нужны в git-репозитории. https://habr.com/post/202696/

**Comment by SergeyKozadaev** [comment]
В файл <a href="https://github.com/SergeyKozadaev/symfonyLibrary/blob/work/.gitignore">.gitignore</a> добавлена строка для игнорирования папки .idea. 
<a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/a4f2090dd2567e98c4bfe59462b72d43cbbd7cce">Коммит issue#1</a>

**Comment by sheerockoff** [comment]
В git есть возможность глобально указать файл для исключения:
```bash
git config --global core.excludesfile "/home/sheerockoff/dev/.gitignore_global"
```
Это лучшее место для указания специфичных для рабочего окружения исключений. И когда ты работаешь со своим проектом. И когда работаешь с чужим проектом. Тебе не придётся править `.gitignore`, потому что другой программист указал в исключениях, например, `.atom/`, которым пользуется он, а не `.idea/`, которой пользуешься ты. А файлы `.gitignore` в проекте лучше использовать для специфичных проекту (а не рабочему окружению программиста) исключений.

https://habr.com/post/202696/

**Comment by SergeyKozadaev** [comment]
Действительно, если в git создать глобальный файл с исключениями и прописать к нему путь(через команду или в  ~/.gitconfig), то это позволит в одном месте указать исключаемые для всех проектов файлы и директории. Честно говоря, не знал раньше о такой возможности. Использовал в проекте, отдельный коммит не создавал.
