### ISSUE TITLE
[code-review] Константа ITEMS_PER_PAGE в контроллере

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#3]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Controller/BookController.php#L19-L21

Кол-во элементов на странице рекомендуется перенести в параметры (`services.yaml`, `.env`) или иной способ представления, который не потребует переписывания исходного кода приложения для изменения такой, достаточно гибкой, настройки.

**Comment by SergeyKozadaev** [comment]
Параметр кол-во элементов на странице был перенесен из файла контроллера в файл конфигурации services.yaml. <a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/d43287e46997cfa7332f4fd239697f1aee2ff1d2">Коммит issue#3</a>
