### ISSUE TITLE
[code-review] PSR-2: должен быть пробел между if и открывающей скобкой

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#4]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Controller/BookController.php#L36

PSR-2 рекомендует ставить пробел после ключевого слова управляющей структуры (if, for, while и т.д.). Цитата: `There MUST be one space after the control structure keyword`.

PSR-2: https://www.php-fig.org/psr/psr-2/#5-control-structures

**Comment by SergeyKozadaev** [comment]
Будет учтено в рамках <a href="https://github.com/SergeyKozadaev/symfonyLibrary/issues/9">issue#9</a>.
