### ISSUE TITLE
[code-review] Вызов echo внутри функции twig

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#6]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Twig/ImageResizeExtension.php#L34-L48

HTML надо вернуть через `return`. Вызов `echo` в этой функции, это рендеринг html в обход шаблонизатора Twig.

**Comment by SergeyKozadaev** [comment]
Внесены необходимые доработки, теперь функция возвращает html через php-конструкцию return. <a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/1222b09d7798e897aaeb7768f00ebacc04891fcb">Коммит issue#6.</a>
