### ISSUE TITLE
[code-review] Тесты будут проваливаться почти в каждом случае

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#7]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/tests/Controller/BookApiControllerTest.php#L9

https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/tests/EventListener/FileClearingSubscriberTest.php#L12

Из-за наличия этих констант в тестах, тесты будут проваливаться почти в каждом случае. Необходимо сделать тесты более автономными. Например, они могут учитывать настройки окружения, или, например, можно создавать книгу перед тестом её удаления.

**Comment by SergeyKozadaev** [comment]
Тесты были <a href="https://github.com/SergeyKozadaev/symfonyLibrary/tree/work/tests">переписаны</a>: 
- в тестах используются параметры из `services.yaml`, а не константы класса;
- тесты стали более автономными: создается и авторизуется пользователь для теста добавления книги, создается книга для теста удаления книги.

Методы `setUp()` и `tearDown()` не использовались.
