### ISSUE TITLE
[code-review] Мёртвый код в репозитории

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#8]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Repository/BookRepository.php#L31-L58

Мёртвый код в репозитории. Нет оснований его хранить. https://github.com/jupeter/clean-code-php#remove-dead-code

**Comment by SergeyKozadaev** [comment]
Мертвый код был удален из репозитория. <a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/42321a1c9afde8b330977f597d7c961a0e61ec60">Коммит issue#8</a>
<a href="https://github.com/jupeter/clean-code-php#remove-dead-code">Рекомендации</a>  по организации и стилю кода изучил.
