### ISSUE TITLE
[code-review] Многочисленные отступления от рекомендаций по стилю кода

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#9]
@SergeyKozadaev писал:
> githooks(https://github.com/intaro/php-git-hooks) не использовался, т.к. в текущем состоянии не является полностью работоспособным

По моему опыту, хук работает, он не даёт сделать коммит, если код не соответствует некоторым рекомендациям по стилю кода.

В проекте есть отступления от этих рекомендаций ([Symfony](https://symfony.com/doc/current/contributing/code/standards), [PSR-1](https://www.php-fig.org/psr/psr-1), [PSR-2](https://www.php-fig.org/psr/psr-2)). Пример не самой очевидной ошибки в стиле:
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Controller/BookApiController.php#L137

Возможно, наличие подобных ошибок можно было спутать с неработоспособностью хука.

Встроенный в phpStorm code formatter может исправить многие из них. Рекомендую также использовать, например, https://cs.sensiolabs.org.

**Comment by SergeyKozadaev** [comment]
<a href="https://github.com/intaro/php-git-hooks">Githooks</a> для Symfony версии 4.* не работал из-за использования <a href="https://github.com/symfony/process/blob/master/CHANGELOG.md">устаревшего класса Symfony\Component\Process\ProcessBuilder</a>. Пример выдаваемого сообщения об ошибке:

```$ git ci -m "useless commit" 
Intaro Code Quality Tool
Fetching files
Check composer
Running PHPLint
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /var/www/php-git-hooks/pre-commit:102
Stack trace:
#0 /var/www/php-git-hooks/pre-commit(38): CodeQualityTool->phpLint(Array)
#1 /var/www/php-git-hooks/vendor/symfony/console/Application.php(145): CodeQualityTool->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/php-git-hooks/pre-commit(185): Symfony\Component\Console\Application->run()
#3 {main}
  thrown in /var/www/php-git-hooks/pre-commit on line 102
```
На текущий момент работоспособность библиотеки восстановлена. 

Рекомендации по оформлению кода(symfony, php) дополнительно изучил. Инструменты для проверки и автоматического форматирования кода буду использовать в процессе разработки. <a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/d9ef877fbbf2fc61ea7b151cb798e8221ba8fd26">Коммит №1</a> и <a href="https://github.com/SergeyKozadaev/symfonyLibrary/commit/d48ff4a837f8c8af172939251e4fab516620aaa7">коммит №2</a>.
